# Generated by Django 5.0.8 on 2026-03-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('citizens', '0002_rename_citizens_ci_ward_na_d42d2e_idx_citizens_ci_ward_na_b46ec7_idx'),
        ('hazards', '0003_rename_hazards_haz_ward_na_9a9f20_idx_hazards_haz_ward_na_f40593_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'channel'], name='alerts_aler_status_4599b1_idx'),
        ),
    ]
