# Generated by Django 5.0.8 on 2026-03-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0002_wardboundary'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hazardobservation',
            new_name='hazards_haz_ward_na_f40593_idx',
            old_name='hazards_haz_ward_na_9a9f20_idx',
        ),
        migrations.RenameIndex(
            model_name='riskassessment',
            new_name='hazards_ris_ward_na_2ab19d_idx',
            old_name='hazards_ris_ward_na_44efff_idx',
        ),
        migrations.RenameIndex(
            model_name='wardboundary',
            new_name='hazards_war_county__60059d_idx',
            old_name='hazards_wa_county__f9d958_idx',
        ),
    ]
