# Generated by Django 5.0.8 on 2026-03-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hazards', '0005_alter_hazardobservation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='data_sources_used',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
