# Generated by Django 5.0.8 on 2026-03-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='citizenprofile',
            new_name='citizens_ci_ward_na_b46ec7_idx',
            old_name='citizens_ci_ward_na_d42d2e_idx',
        ),
    ]
