# Generated by Django 5.0.8 on 2026-03-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rescueunit',
            new_name='rescue_resc_unit_ty_68dee2_idx',
            old_name='rescue_resc_unit_ty_b23fc6_idx',
        ),
    ]
